### ISSUE TITLE
COM AI plays twice at the start of the game if it goes first

### ISSUE THREAD

**Issue by NARUDESIGNS** [NARUDESIGNS/tic-tac-toe#1]
### The Problem
The AI plays twice when I select the `O` marker (which makes it play first as `X` goes first).
This might be a rendering issue. 

### Steps to Reproduce Issue
* Select `O` marker
* Select `COM` as the opponent
* Click the `START` button to launch the game

See screenshots: 
<img width="830" alt="Screenshot 2022-04-10 at 10 49 11 AM" src="https://user-images.githubusercontent.com/49737323/162612635-8fc52088-efc2-46e1-bf87-440febe6b23a.png">

<hr>

<img width="781" alt="Screenshot 2022-04-10 at 10 49 22 AM" src="https://user-images.githubusercontent.com/49737323/162612676-9c0591aa-f3ae-48f9-9cc5-74ad73504949.png">

**Comment by kcde** [comment]
``` javascript
// Check if human is playing against com
  useEffect(() => {
    if (opponent === 'COM' && !turn) comAi(turn, boardState, rules, handleClick, roundIsCompleted);
  }, [turn]);

  // play and allow next turn
  useEffect(() => {
    let isMounted = true;
    // check if all spots has some value but no winner, game result is a tie 
    if (isMounted && (winPattern.length < 1) && (boardState.every(spot => spot !== ''))) {
      setTies(prevState => prevState + 1);
      setFinalResult("It's a tie");
      resetGame();
    } else if (isMounted && boardState.some(spot => spot !== '')) play(); // next player's turn
    return () => {
      isMounted = false;
      clearTimeout(timeout);
    }
  }, [boardState]);
```
The problem is coming from the order the useEffects are called.
If I'm not mistaken, the first useEffect checks if you select the Ai as an opponent and also checks if it's its turn. if it is, it plays using the comAi function.

When Game.js mounts, following how the useEffects are called, the comAI plays and   the "else if" statement in the second useEffect will evaluate to false which won't call the ```play()``` function that toggles the ```turn``` value.  But comAi will cause ```boardState``` to update through the ```handleClick()``` function which will in effect cause a rerender of the component and since ```turn``` is still false, comAi will play again. By this second rerender, the "else if" statement in the second useEffect will evaluate to true which then calls the ```play()```  function. 
 
 please do ask if my explanation is not quite clear.
 
 in the meantime, I have remedied this bug and would like to make a pull request. Hope that is fine.

**Comment by NARUDESIGNS** [comment]
Thank you so much for your explanation and also for contributing. I understand your explanation.
Please go ahead and I'd check out your PR to see if it fixes the issue.

Thanks again!
